#!/usr/bin/env bash
set -euo pipefail
# Generated by run_e10_external_dataset_asset_audit.py
# Large files are intentionally not downloaded automatically by the audit.
DEST_ROOT="/home/yyf/data/singlecell_perturbation_atlas"
mkdir -p "$DEST_ROOT"
