#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
Run the SafeTrans confidence scoring MVP.

Environment variables:
  PROJECT_ROOT   Project directory.
  PYTHON_BIN     Python executable.
  STOP_AFTER_RECORDS=1  Stop after Step 4.
EOF
  exit 0
fi

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PYTHON_BIN="${PYTHON_BIN:-/home/yyf/.conda/envs/scgpt_env/bin/python}"
OUT_DIR="$PROJECT_ROOT/outputs/confidence_task_mvp"
LOG_DIR="$OUT_DIR/logs"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/run_mvp.log"

exec > >(tee -a "$LOG") 2>&1
echo "[run_mvp] start $(date)"

"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/build_heldout_pair_split.py"
"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/run_predictors.py"
"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/build_prediction_records.py"

if [[ "${STOP_AFTER_RECORDS:-0}" == "1" ]]; then
  echo "[run_mvp] stopped after Step 4 by STOP_AFTER_RECORDS=1"
  exit 0
fi

"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/compute_confidence_features.py"
"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/run_confidence_scores.py"
"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/evaluate_confidence.py"
"$PYTHON_BIN" "$PROJECT_ROOT/confidence_task/plot_confidence_results.py"

cat > "$OUT_DIR/MVP_REPORT.md" <<'EOF'
# Confidence scoring MVP report

This report is generated by run_mvp.sh after the full MVP pipeline. The current user-requested run stopped after Step 4 unless STOP_AFTER_RECORDS was unset.
EOF

echo "[run_mvp] done $(date)"
