task_name: train
train: true
test: false
ckpt_path: null
seed: 245
data:
  transform:
    conf:
      _target_: perturbench.data.transforms.pipelines.LinearModelPipelineControls
      _partial_: true
    dependencies:
      perturbation_uniques: perturbation_uniques
      covariate_uniques: covariate_uniques
      use_perturbation_embedding: use_perturbation_embedding
  splitter:
    split_path: /home/yyf/data/perturbench_mcfaline23_official/splits/mcfaline23_gxe_splits/full_covariate_split.csv
  evaluation:
    split_value_to_evaluate: val
    test_data_iter_factory:
      _target_: perturbench.data.datasets.CounterfactualWithReference.from_anndata
      _partial_: true
      max_control_cells_per_covariate: 1000
      perturbation_key: ${data.data_iter_factory.perturbation_key}
      perturbation_control_value: ${data.data_iter_factory.perturbation_control_value}
      covariate_keys: ${data.data_iter_factory.covariate_keys}
      embedding_key: ${data.data_iter_factory.embedding_key}
      feature_filter_path: ${data.data_iter_factory.feature_filter_path}
      seed: ${seed}
    evaluation_pipelines:
    - aggregation: average
      metric: rmse
      rank: true
    - aggregation: pca_average
      metric: cosine
      rank: true
    - aggregation: logfc
      metric: cosine
      rank: true
    - aggregation: scores
      metric: r2_score
      rank: false
    - aggregation: scores
      metric: top_k_recall
      rank: false
    - aggregation: pca
      metric: mmd
      rank: true
    save_evaluation: true
    save_dir: ${paths.output_dir}/evaluation/
    chunk_size: 5
    print_summary: true
    use_synthetic_controls: false
    use_control_variance: false
    run_cell_eval: true
  _target_: perturbench.data.modules.AnnDataLitModule
  data:
    filename: ${paths.data_dir}/mcfaline23_gxe_processed.h5ad
  data_iter_factory:
    _target_: perturbench.data.datasets.SingleCellPerturbationWithControls.from_anndata
    _partial_: true
    perturbation_key: condition
    perturbation_combination_delimiter: +
    perturbation_control_value: control
    covariate_keys:
    - cell_type
    - treatment
    embedding_key: null
    feature_filter_path: null
  mode: batch
  loader:
    batch_size: 8000
    num_workers: 0
model:
  _target_: perturbench.modelcore.models.LatentAdditive
  n_genes: null
  n_perts: null
  lr: 0.00046952967507921957
  wd: 3.348258680704949e-08
  n_layers: 1
  encoder_width: 4352
  latent_dim: 256
  softplus_output: true
  inject_covariates_encoder: true
  inject_covariates_decoder: true
  dropout: 0.1
callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 50
  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    log_momentum: true
    logging_interval: epoch
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_loss
    dirpath: ${hydra:runtime.output_dir}/checkpoints
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
logger:
  tensorboard:
    _target_: lightning.pytorch.loggers.TensorBoardLogger
    save_dir: ${paths.output_dir}
    name: tensorboard/
    prefix: ''
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
    save_dir: ${paths.output_dir}
    name: csv/
    prefix: ''
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 5
  max_epochs: 500
  accelerator: gpu
  devices: 1
  precision: 16
  check_val_every_n_epoch: 1
  deterministic: false
  log_every_n_steps: 10
paths:
  data_dir: /home/yyf/data/perturbench_mcfaline23_official
  log_dir: ./logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
